/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/common/AboutModal.vue')['default']
    DesktopLyrics: typeof import('./src/components/lyrics/DesktopLyrics.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    FavoriteButton: typeof import('./src/components/common/FavoriteButton.vue')['default']
    GlobalPlayer: typeof import('./src/components/player/GlobalPlayer.vue')['default']
    PlaybackControls: typeof import('./src/components/player/PlaybackControls.vue')['default']
    ProgressBar: typeof import('./src/components/player/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectModal: typeof import('./src/components/common/SelectModal.vue')['default']
    SettingsModal: typeof import('./src/components/common/SettingsModal.vue')['default']
    ShortcutSettings: typeof import('./src/components/common/ShortcutSettings.vue')['default']
    Timestamp: typeof import('./src/components/player/Timestamp.vue')['default']
    VolumeControl: typeof import('./src/components/player/VolumeControl.vue')['default']
  }
}
